<div class="col-sm-4">
    <h2>This is main title</h2>
    <ol class="breadcrumb">
        <?php
        // iterate through the pages
        foreach ($this->pages as $key => $page):
        ?>
            <li>
                <?php
                // if this isn't the last page, add a link and the separator:
                if ($key < count($this->pages) - 1):
                ?>
                    <a href="<?= $page->getHref() ?>"><?= $page->getLabel() ?></a>
                <?php
                // otherwise, output the name only:
                else:
                ?>
                    <?= $page->getLabel() ?>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ol>
</div>