version: '3'
services:
  web:
    container_name: zend_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - '8000:80'
    links:
      - php
  php:
    container_name: zend_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./:/var/www/html
    links:
      - db
  db:
    container_name: zend_postgres
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/zend_reenactment
    ports:
      - '5432:5432'
