<div class="row">
    <div class="col-lg-5">
        <div class="ibox">
            <div class="ibox-title">
                <h5>Delete User</h5>
            </div>
            <div class="ibox-content">
                <p> Are you sure that you want to delete? </p>
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>E-mail</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><?= $this->escapeHtml($this->user->getId()) ?></td>
                            <td><?= $this->escapeHtml($this->user->getEmail()) ?></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <form action="<?= $this->url('user', ['action' => 'delete', 'id' => $this->id]); ?>" method="post">
                    <div class="form-group ">
                        <input type="hidden" name="id" value="<?= (int)$this->user->getId() ?>"/>
                        <button class="btn btn-danger" name="del" id="deleteUser" value="Delete">Delete</button>
                        <button class="btn btn-default" name="del" value="Cancel">Cancel</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
