<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title text-right">
                <a class="btn btn-primary" href="<?= $this->url('user', ['action' => 'add']); ?>">
                    <i class="fa fa-plus"></i> Add User
                </a>
            </div>
            <div class="ibox-content">

                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTables-example">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>E-mail</th>
                            <th>&nbsp;</th>
                        </tr>
                        </thead>
                        <?php foreach ($this->users as $user): ?>
                            <tbody>
                            <tr>
                                <td><?= $this->escapeHtml($user->getId()); ?></td>
                                <td><a href="<?= $this->url('user', ['action'=>'delete', 'id'=>$user->getId()]); ?>">
                                        <?= $this->escapeHtml($user->getEmail()); ?>
                                    </a>
                                </td>

                                <td class="text-right">
                                    <a class="btn-sm btn-danger" href="<?= $this->url('user', ['action' => 'delete', 'id' => $user->getId()]); ?>">
                                        <i class="fa fa-times"></i> Delete </a>
                                </td>
                            </tr>

                            </tbody>
                        <?php endforeach; ?>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>