<?php
/** @var \User\Form\LoginForm $form */
use Zend\Mvc\Plugin\FlashMessenger\FlashMessenger;

$form = $this->form;
$form->setAttribute('action', $this->url('user', ['action' => 'login']));

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Email address',
]);

$form->get('password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Password',
]);

$form->prepare();


$this->flashMessenger()
    ->setMessageOpenFormat('<div%s><p>')
    ->setMessageSeparatorString('</p><p>')
    ->setMessageCloseString('</p></div>');
?>


<div class=" middle-box animated fadeInDown text-center mtop">
    <?= $this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR, array('alert', 'alert-danger')); ?>
    <div>

        <div class="ibox-content">
            <p>Login in. To see more.</p>

            <?= $this->form()->openTag($form); ?>
            <div class="form-group">
                <?= $this->formElement($form->get('email')); ?>
            </div>
            <div class="form-group">
                <?= $this->formElement($form->get('password')); ?>
            </div>
            <?= $this->formElement($form->get('csrf')) ?>
            <input type="submit" value="Login" name="buttonEnter" class="btn btn-primary block full-width m-b">

            <?= $this->form()->closeTag(); ?>

        </div>
    </div>
</div>


