<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">Name</strong>
                             </span> <span class="text-muted text-xs block">Admin<b class="caret"></b></span> </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="<?= $this->url('user', ['action' => 'logout']); ?>">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    Ree
                </div>
            </li>
            <li>
                <a href="<?= $this->url('home'); ?>"><i class="fa fa-home"></i> <span class="nav-label">Home</span></a>
            </li>
            <li class="active">
                <a href=""><i class="fa fa-user"></i> <span class="nav-label">User</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a href="<?= $this->url('user'); ?>">User</a></li>
                    <li><a href="<?= $this->url('user', ['action' => 'add']); ?>">Add</a></li>
                    <li><a href="<?= $this->url('user', ['action' => 'delete']); ?> ">Delete</a></li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

<div id="page-wrapper" class="gray-bg">
    <div class="row border-bottom">
        <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                <form role="search" class="navbar-form-custom" method="post" action="#">
                    <div class="form-group">
                        <input type="text" placeholder="Search for something..." class="form-control" name="top-search"
                               id="top-search">
                    </div>
                </form>
            </div>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <span class="m-r-sm text-muted welcome-message">Welcome to Admin Theme.</span>
                </li>
                <li>
                    <a href="<?= $this->url('user', ['action' => 'logout']); ?>">
                        <i class="fa fa-sign-out"></i> Log out
                    </a>
                </li>
            </ul>

        </nav>
    </div>
    <div class="row wrapper border-bottom white-bg page-heading">

        <?= $this->navigation('navigation')
            ->breadcrumbs()
            ->setLinkLast(true)
            ->setMinDepth(0)
            ->setPartial('partial/breadcrumb') ?>
        <div class="col-lg-2">

        </div>
    </div>




