<?php

use Zend\View\Helper\Doctype;

$this->headTitle('Reenactment')->setSeparator(' - ')->setAutoEscape(false);

$this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');

$this->headLink()
    ->appendStylesheet('/assets/css/bootstrap.min.css')
    ->appendStylesheet('/assets/font-awesome/css/font-awesome.min.css')
    ->appendStylesheet('/assets/css/plugins/iCheck/custom.css')
    ->appendStylesheet('/assets/css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css')
    ->appendStylesheet('/assets/css/plugins/dataTables/datatables.min.css')
    ->appendStylesheet('/assets/css/animate.css')
    ->appendStylesheet('/assets/css/style.css');

$this->inlineScript()
    ->appendFile('/assets/js/jquery-3.1.1.min.js')
    ->appendFile('/assets/js/plugins/validate/jquery.validate.min.js')
    ->appendFile('/assets/js/bootstrap.min.js')
    ->appendFile('/assets/js/plugins/metisMenu/jquery.metisMenu.js')
    ->appendFile('/assets/js/plugins/slimscroll/jquery.slimscroll.min.js')
    ->appendFile('/assets/js/plugins/dataTables/datatables.min.js')
    ->appendFile('/assets/js/inspinia.js')
    ->appendFile('/assets/js/plugins/pace/pace.min.js')
    ->appendFile('/js/default.js');

?>
<?= $this->doctype(Doctype::HTML5) ?>
<html>
<head>
    <?= $this->headTitle() ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
</head>
<body class="smoothscroll enable-animation">

<div id="wrapper">
    <?= $this->partial('_header.phtml'); ?>


    <div class="wrapper-content animated fadeInRight">
        <?= $this->content ?>
    </div>

    <?= $this->partial('_footer.phtml'); ?>
</div>
<a href="#" id="toTop"></a>
<div id="preloader">
    <div class="inner">
        <span class="loader"></span>
    </div>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
